import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-700 text-white">
        <main className="container flex justify-center items-center mx-auto px-4 py-8 h-full">
          {children}
        </main>
      </body>
    </html>
  );
}
